// Root build. Plugin declarations with apply=false put the plugin artifact on every
// subproject's buildscript classpath so convention plugins can apply them programmatically.
plugins {
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.androidKmpLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinJvm) apply false
    alias(libs.plugins.kotlinSerialization) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.ktlint) apply false
}

// ── Quality gates — applied to every Kotlin subproject ────────────────────────
subprojects {
    // ktlint: code style enforcement (line length, imports, formatting)
    apply(plugin = "org.jlleitschuh.gradle.ktlint")
    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set("1.5.0")
        android.set(false)      // KMP project — don't inject android-specific rules
        outputToConsole.set(true)
        filter {
            exclude("**/build/**/*.kt")
            exclude("**/generated/**/*.kt")
        }
    }

    // detekt: static analysis
    apply(plugin = "dev.detekt")
    configure<dev.detekt.gradle.extensions.DetektExtension> {
        config.setFrom(rootProject.files("config/detekt/detekt.yml"))
        buildUponDefaultConfig = true
        parallel = true
        // detekt 2.x's default ruleset + renamed rules surfaced pre-existing findings that
        // 1.23.x's config didn't catch; baseline grandfathers those in, new code is still gated.
        baseline = file("detekt-baseline.xml")
        // Only scan hand-authored source; skip generated + build output
        source.setFrom(
            "src/commonMain/kotlin",
            "src/androidMain/kotlin",
            "src/jvmMain/kotlin",
            "src/iosMain/kotlin",
            "src/wasmJsMain/kotlin",
        )
    }
}

// CVE fix: ws < 8.21.0 is a high-severity memory-exhaustion DoS. It arrives transitively through
// Ktor's wasm client, whose generated package.json pins `"ws": "8.20.1"` *exactly* — so editing
// kotlin-js-store/wasm/yarn.lock by hand cannot hold: the lock key is the requested descriptor, and
// yarn re-resolves 8.20.1 the moment the two disagree. A Yarn resolution is the only lever.
//
// Wasm has its own Yarn root, separate from JS: `WasmYarnRootExtension`, regenerated by
// `kotlinWasmUpgradeYarnLock` (NOT `kotlinUpgradeYarnLock`, which only touches kotlin-js-store/ and
// reports BUILD SUCCESSFUL without touching the wasm lock at all).
//
// The generated build/wasm/package.json is what carries `resolutions` — if it is stale it keeps an
// empty map and the resolution looks broken when it is not. Verify the fix at the artefact, not the
// exit code: `resolutions` in build/wasm/package.json, `version "8.21.0"` in the lock, and the
// version in build/wasm/node_modules/ws/package.json.
plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin> {
    the<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension>().resolution("ws", "8.21.0")
}
