plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.kotlinSerialization)
    application
}

application {
    mainClass.set("com.kursi.server.AppKt")
}

kotlin {
    jvmToolchain(21)
}

// ── Three-tier versioning ──────────────────────────────────────────────────────
// Stamps FINGERPRINT into a generated BuildInfo.kt consumed by the /version endpoint.
// See gradle/versioning.gradle.kts + docs/RELEASE.md.
apply(from = "$rootDir/gradle/versioning.gradle.kts")
val kursiFingerprintVersion = extra["kursiFingerprint"] as String
val generatedVersionDir = layout.buildDirectory.dir("generated/kursiVersion/kotlin")
val generateBuildInfo by tasks.registering {
    val outputDir = generatedVersionDir
    val fingerprint = kursiFingerprintVersion
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile.resolve("com/kursi/server/BuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.kursi.server

            /** Generated by :server versioning — see gradle/versioning.gradle.kts. Do not edit. */
            object BuildInfo {
                const val FINGERPRINT: String = "$fingerprint"
            }

            """.trimIndent(),
        )
    }
}
sourceSets.main { kotlin.srcDir(generatedVersionDir) }
tasks.named("compileKotlin") { dependsOn(generateBuildInfo) }

dependencies {
    implementation(project(":engine"))
    implementation(project(":shared-protocol"))
    implementation(project(":ai"))

    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    implementation(libs.ktor.server.websockets)
    implementation(libs.ktor.server.contentNegotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.server.statusPages)
    implementation(libs.kotlinx.coroutines.core)

    runtimeOnly(libs.logback.classic)

    testImplementation(libs.ktor.server.testHost)
    testImplementation(kotlin("test"))
    testImplementation(libs.kotlinx.coroutines.test)
    // M7: drive the REAL :core:network client against a real embedded Netty server (round-trip test).
    testImplementation(project(":core:network"))
    testImplementation(libs.ktor.client.okhttp)
}
