import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

kotlin {
    jvm()

    sourceSets {
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(project(":cmp-shared"))
            implementation(project(":feature:game"))
            implementation(project(":core:designsystem"))
            implementation(project(":core:prefs"))
            implementation(project(":core:network"))
            implementation(project(":engine"))
            implementation(project(":ai"))
        }
    }
}

// ── Headless screenshot task ───────────────────────────────────────────────────
tasks.register<JavaExec>("renderScreens") {
    group = "kursi"
    description = "Render GameScreen fixture states to PNG files in build/shots/"
    mainClass.set("com.kursi.desktop.ScreenshotsKt")
    classpath = configurations["jvmRuntimeClasspath"] +
        kotlin.targets
            .named("jvm")
            .get()
            .compilations
            .named("main")
            .get()
            .output.allOutputs
    val shotsDir =
        layout.buildDirectory
            .dir("shots")
            .get()
            .asFile
    systemProperty("kursi.shots.dir", shotsDir.absolutePath)
    doFirst { shotsDir.mkdirs() }
    dependsOn("jvmMainClasses")
}

compose.desktop {
    application {
        mainClass = "com.kursi.desktop.MainKt"

        jvmArgs("-Xmx512m")

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)

            packageName = "Kursi"
            packageVersion = "1.0.0"
            description = "Bluffing card game — Kursi ke liye kuch bhi karega."
            copyright = "© 2025 Siddharth Pandalai"
            vendor = "darkpandawarrior"

            // Icons are generated by scripts/generate_icons.sh — run it once before
            // packaging. Conditional so compilation still works without the files.
            val iconsDir = project.file("src/jvmMain/resources/icons")
            macOS {
                iconsDir.resolve("kursi.icns").takeIf { it.exists() }?.let { iconFile.set(it) }
                bundleID = "com.kursi.desktop"
                packageVersion = "1.0.0"
                dmgPackageVersion = "1.0.0"
                infoPlist {
                    extraKeysRawXml =
                        """
                        <key>NSHighResolutionCapable</key><true/>
                        """.trimIndent()
                }
            }
            windows {
                iconsDir.resolve("kursi.ico").takeIf { it.exists() }?.let { iconFile.set(it) }
                packageVersion = "1.0.0"
                msiPackageVersion = "1.0.0"
                menuGroup = "Kursi"
                upgradeUuid = "2E5F3A1C-9B4D-4E7A-8C0F-1D2B3E4A5F6C"
            }
            linux {
                iconsDir.resolve("kursi_512.png").takeIf { it.exists() }?.let { iconFile.set(it) }
                packageVersion = "1.0.0"
                debPackageVersion = "1.0.0"
                menuGroup = "Game"
            }
        }
    }
}
